go_import_path: github.com/comcast/viper


language: go

go:
  - 1.11.x
  - tip

os:
  - linux
  - osx


matrix:
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - go get -u github.com/golang/dep/...
  - dep ensure

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - go test -v -race $(go list ./... | grep -v "/vendor/")
  - go get github.com/haya14busa/goverage
  - goverage -coverprofile=coverage.txt ./...

after_success:
  -  bash <(curl -s https://codecov.io/bash)